### ISSUE TITLE
The requested package fabarea/sculpin-pages-bundle could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by carbontwelve** [fabarea/sculpin-pages-bundle#2]
Looks like the package isn't on packagist.org and therefore composer cant see it.

To get it working I had to manually add the package path to the `sculpin.json` file like so:

```
...
"repositories": [
        {
            "type":"vcs",
            "url":"https://github.com/fabarea/sculpin-pages-bundle"
        }
    ],
...
```

**Comment by fabarea** [comment]
Well, I wasn't sure this experimental Bundle had enough value to be brought to Packagist. Since you mentioned, I did https://packagist.org/packages/fab/sculpin-pages-bundle

**Comment by carbontwelve** [comment]
Well it is both a interesting learning resource and a useful bundle to have; regardless of its experimental status it does have value :)
